# Change these first
owner: ch7aki # Your GitHub organization or username, where this repository lives
repo: status # The name of this repository

sites:
  - name: blog_A
    url: https://ch7aki.com
  - name: blog_B
    url: https://ch7aki-life.com

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  # cname: demo.upptime.js.org
  baseUrl: /status
  logoUrl: https://raw.githubusercontent.com/ch7aki/status/master/assets/avatar.jpg
  name: ch7aki's status
  introTitle: "ch7aki's status"
  navbar:
    - title: status
      href: /status
    - title: blog_A
      href: https://ch7aki.com
    - title: blog_B
      href: https://ch7aki-life.com
    - title: status
      href: https://github.com/$OWNER/$REPO
i18n:
  footer: <small>Powered by <a href="https://ch7aki.com"><strong>ch7aki</strong></a>.</small>

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
